media:
  input: docs/images
  output: images
  
content:
  - name: home
    label: Accueil
    path: docs/index.md
    type: file
  - name: team
    label: Equipe
    path: docs/equipe.md
    type: file   
  - name: contact
    label: Contact
    path: docs/contact.md
    type: file
  - name: logs
    label: On parle de nous
    path: docs/journaux.md
    type: file
  - name: event
    label: Evenements
    path: docs/evenements.md
    type: file
    
  - name: recettes
    label: Recettes
    path: docs/recettes
    type: collection
    fields: 
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text    
    view:
      fields: [ title, date ]
      sort: [ date, title ]
       
  - name: verger
    label: Vergers
    path: docs/vergers
    type: collection
    fields: 
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text      
  - name: varietes
    label: Varietes
    path: docs/varietes
    type: collection
    fields: 
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: variete
        label: Variete
        type: string
      - name: body
        label: Body
        type: rich-text      

  
  # - name: falling-fruit
  #   label: Zone de Glanage
  #   path: docs/falling_fruit
  #   type: collection    
