media:
  input: docs/images
  output: images
  
content:
  - name: home
    label: Accueil
    path: docs/index.md
    type: file
  - name: team
    label: Equipe
    path: docs/equipe.md
    type: file   
  - name: contact
    label: Contact
    path: docs/contact.md
    type: file
  - name: logs
    label: On parle de nous
    path: docs/journaux.md
    type: file
  - name: event
    label: Evenements
    path: docs/evenements.md
    type: file
    
  - name: recettes
    label: Recettes
    path: docs/recettes
    type: collection
    fields: [ title, date, author ]
    view:
      fields: [ title, date, published ] # title is the first entry and thus will be set to primary
      sort: [ date, title, published ]
 
        
  - name: verger
    label: Vergers
    path: docs/vergers
    type: collection
  - name: varietes
    label: Varietes
    path: docs/varietes
    type: collection

  
  
  - name: falling-fruit
    label: Zone de Glanage
    path: docs/falling_fruit
    type: collection    
