extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/afaucogney
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Tous-Au-Verger-106680710873061/
      
site_name: Tous au Verger
site_url: https://afaucogney.github.io/Tous-Au-Verger/
site_description: "Une assocation qui valorise les fruitiers delaissés"
site_author: Anthony Faucogney
remote_branch: gh-pages

theme:
  name: material
  language: fr
  palette:
    primary: 'green'
    accent: 'light-red'
  favicon: 'images/favicon.png'
  logo: 'images/logo.jpg'

markdown_extensions:
  - pymdownx.emoji
  
plugins:
  - search  